# vim: set ft=dockerfile :
FROM python as no-dev
WORKDIR /app

RUN pip3 install poetry

COPY ./poetry.lock ./pyproject.toml /app/
RUN poetry install --no-dev


FROM no-dev as dev
WORKDIR /app

ENV PYTHONUNBUFFERED=1

RUN poetry install

EXPOSE 8080
ENTRYPOINT ["poetry", "run", "more-one-memo_web"]


FROM no-dev as prod
WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY ./more_one_memo /app/more_one_memo

EXPOSE 8080
ENTRYPOINT ["poetry", "run", "more-one-memo_web"]
