# vim: set ft=dockerfile :
FROM python as no-dev
WORKDIR /app

RUN pip3 install poetry

COPY ./poetry.lock ./pyproject.toml /app/
COPY ./more_one_memo /app/more_one_memo
RUN poetry install


FROM no-dev as dev
WORKDIR /app

ENV PYTHONUNBUFFERED=1

RUN poetry install --with dev

ENTRYPOINT ["poetry", "run", "more-one-memo_forwarder"]


FROM no-dev as prod
WORKDIR /app

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["poetry", "run", "more-one-memo_forwarder"]
